### ISSUE TITLE
Possibility of this source code

### ISSUE THREAD

**Issue by BarryV94** [TheTangyLemon/Obsidian#1]
hey i was thinking maybe you can fuse together :
- https://github.com/RX14/jMCLaunchLib  - ( This one works only for versions 1.12.2 )
and your Obsidian to make one of the best MinecraftLaunchLib to make your own launchers for minecraft it would be the best of the launchlibs.

is there any way to contact with you? via email or something ?

**Comment by TheTangyLemon** [comment]
This launcher is not done yet, I still have to work on library downloading and actually launching it. I will look into jMCLaunchLib to see if I can include it.

**Comment by TheTangyLemon** [comment]
Obsidian will also probably just be command line only, just to let you know. I'm new to Java coding and all this stuff.

**Comment by BarryV94** [comment]
Ohh ok than i am waiting, maybe you will make the best Lib to make custom minecraft launchers :)

**Comment by TheTangyLemon** [comment]
Yeah I was thinking of doing something like that, maybe it would be called libobsidian.

**Comment by BarryV94** [comment]
than waiting :D

**Comment by TheTangyLemon** [comment]
You (and anyone else) can contact me at my git commit email tangylemon345@gmail.com.
